on:
  pull_request:
    types:
      - opened

jobs:
  test_contribs:
    if: github.event.pull_request.base.ref == 'contribs'
    runs-on: ubuntu-latest
    steps:
      - name: ansible-lint
        uses: ansible/ansible-lint-action@v4.1.0.post0
        with:
          target: playbooks/acs.yml
      - name: Pylint action
        uses: gabriel-milan/action-pylint@v1
        with:
          path: "roles/*/molecule/*/*/*.py"
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.0 
